### ISSUE TITLE
Update to work with latest version of pytest

### ISSUE THREAD

**Issue by allenporter** [oprypin/pytest-golden#2]
When attempting to install with pip and a new version of pytest, pytest-golden 
```
ERROR: Cannot install pytest-golden==0.2.1 and pytest==7.1.2 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested pytest==7.1.2
    pytest-golden 0.2.1 depends on pytest<7.0.0 and >=6.1.2

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

I didn't see anything in the project that limits the version of pytest and the tests seemed to run just fine when i forked the repo. Is this constraint being added somewhere in the release process?

**Comment by oprypin** [comment]
Ah it's just that haven't made a release with https://github.com/oprypin/pytest-golden/commit/99dbd7ef40028acd5e5f9f839cc410f84b3833f0
I'll do that now

**Comment by allenporter** [comment]
Thank you, confirmed working.
